Update documentation and add staging deployment
pharmaverse/pharmaverse pull request #324
Opened 2024-10-01 11:03 UTC by sankhadeepdutta

# Pull Request
Closes #315, #318

- [x] This is a PR into production (main), and I am doing it from develop (NA for this PR)
- [x] If from develop, I have checked the code is working on the UAT site https://pharmaverse-staging-test.netlify.app/

# Description
- [x] Restructured and updated `README.md` and `CONTRIBUTING.md` file contents
- [x] Update pipeline
  - [x] Update versions for `actions/checkout`, `peaceiris/actions-hugo` and `peaceiris/actions-gh-pages`
  - [x] Add `Netlify` deployment for staging

## Metadata

Please reference any related issues here (using `#issuenumber`): #315, #318 
People to notify: @website-maintainers

2024-10-24 09:24 UTC, epijim requested changes
@sankhadeepdutta - could you please review the comment about latest vs locked hugo?

2024-10-24 09:24 UTC, epijim commented on .github/workflows/pipeline.yml
> +          hugo-version: 'latest'
Should we lock this to Hugo version as of today, to avoid errors popping up if something gets deprecated?

Latest scares me 😆

2024-10-24 09:24 UTC, epijim commented
hey @sankhadeepdutta - sorry this took so long, please do feel free to get a review from anyone on the @pharmaverse/website-maintainers team rather than waiting on me.

2024-10-28 07:53 UTC, f-meister requested changes
Besides the hugo version, I see some cleaning up to do on commented code. Also best to check for versions so we can lock them down to a specific one.

2024-10-28 07:53 UTC, f-meister commented on .github/workflows/pipeline.yml
@sankhadeepdutta In line 35, we should really remove that commented code once we've tested and confirmed the badge updates in this repo.

2024-10-28 07:53 UTC, f-meister commented on .github/workflows/pipeline.yml
> +          hugo-version: 'latest'
@sankhadeepdutta From testing locally, looks like we're working with "0.136.5" here

2024-10-28 11:09 UTC, sankhadeepdutta commented on .github/workflows/pipeline.yml
> +          hugo-version: 'latest'
As we are using hugo-extended, I have locked its version to the latest one i.e. 0.119.0

2024-10-28 11:11 UTC, sankhadeepdutta commented on .github/workflows/pipeline.yml
I have pulled the latest changes to the badges script 👍🏻

2024-10-29 02:25 UTC, f-meister approved these changes
LGTM.

2024-10-29 09:09 UTC, rossfarrugia commented
@f-meister @sankhadeepdutta feel free to merge this and then merge a PR to main. You both should have the necessary access level for this repo. Then you can double check all works fine.

2024-10-29 11:12 UTC, merged